version: '3.9'

services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tukach
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: postgres -p 5432